packages: []
catalogs:
  build:
    '@vitejs/plugin-vue': ^6.0.5
    unplugin-icons: ^23.0.1
    vite: ^8.0.0
    vite-plugin-electron: ^0.29.1
    vite-plugin-electron-renderer: ^0.14.6
  dev:
    bumpp: ^10.4.1
    electron: ^41.0.2
    electron-builder: ^26.8.1
    pncat: ^0.10.2
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsx: ^4.21.0
    typescript: ^5.9.3
  frontend:
    '@unocss/reset': ^66.6.6
    unocss: ^66.6.6
    vue: ^3.5.30
  lint:
    '@octohash/eslint-config': ^0.2.3
    '@unocss/eslint-plugin': ^66.6.6
    eslint: ^10.0.0
    lint-staged: ^16.2.7
    vue-tsc: ^3.2.5
  test:
    vitest: ^4.0.18
  types:
    '@types/node': ^25.3.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - electron
  - electron-winstaller
